In [1]:
import numpy as np

In [3]:
  #creating array  with arrange function of numpy
  a=np.arange(15) #single dimensional
  a=np.arange(15).reshape(3,5) #multi dimensional

In [4]:
#size of aray
a.size

15

In [5]:
#dimensions of array
a.ndim

2

In [6]:
#datatype of array
a.dtype

dtype('int32')

In [9]:
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [57]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
#creating array from a iterator
list_b = [1,2,3,4,5,6,7,8,9]
b= np.array (list_b).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#creating multi-dimension array from a iterator
b=np.array([(1.5,2,3),(4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [15]:
#dtype can also be specified
c=np.array([[1,2],[3,4]],dtype=complex)
print(b)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [27]:
#arra of zeros
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
#array of ones
ones=np.ones((2,3,4),dtype= np.int16)
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [24]:
#custom range
cd=np.arange(0,2,0.3)
print(cd)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [23]:
#getting the required number of elements
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
a = np.array([20,30,40,50])
b = np.arange(4) #array ([0,1,2,3])
c = a-b #output  :array([20,29,38,47])
print(c)

[20 29 38 47]


In [32]:
b**2 #output :array ([1,1],[0,1])
10*np.sin(a) #output:array ([9,12945251,-9.88031624,7.4511316,-2.62374854])
a<35 #output :array ([true,true,false,false])

array([ True,  True, False, False])

In [51]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
prod1 =a*b
prod2 = a@b
prod3=a.dot(b)
print(prod1)
print(prod2)
print(prod3)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [52]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
b+=a
print(a)
print(b)

[[3 3 3]
 [3 3 3]]
[[3.90190003 3.18122306 3.03709414]
 [3.73228059 3.80972028 3.7769112 ]]


In [41]:
a = np.random.random((2,3))
a.sum()
a.min()
a.max()

0.9052221253737571

In [43]:
b[0:5,1] #each row in the second column of b

array([3.88192472, 3.50854877])

In [44]:
b[:,1] #equivalent to the previous example 

array([3.88192472, 3.50854877])

In [45]:
b[1:3,:] #each colum in the second and third row of  b

array([[3.72621519, 3.50854877, 3.63919264]])

Stacking arrays

In [50]:
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))
print(a)
print(b)

[[8. 4.]
 [4. 4.]]
[[5. 8.]
 [2. 3.]]


In [47]:
#stacking vertically
np.vstack((a,b))

array([[5., 3.],
       [9., 2.],
       [3., 7.],
       [7., 8.]])

In [48]:
#stacking horizontally
np.stack((a,b))

array([[[5., 3.],
        [9., 2.]],

       [[3., 7.],
        [7., 8.]]])

Splitting Array

In [53]:
a=np.floor(10*np.random.random((2,12)))

In [54]:
#split a into 3
np.hsplit(a,3)

[array([[1., 7., 4., 2.],
        [3., 2., 8., 5.]]),
 array([[2., 4., 2., 9.],
        [5., 1., 3., 6.]]),
 array([[0., 2., 6., 6.],
        [5., 6., 2., 3.]])]

In [55]:
#split a after the third an the fourth column
np.hsplit(a,(3,4))

[array([[1., 7., 4.],
        [3., 2., 8.]]),
 array([[2.],
        [5.]]),
 array([[2., 4., 2., 9., 0., 2., 6., 6.],
        [5., 1., 3., 6., 5., 6., 2., 3.]])]